name:Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - name: Build Electron App
        run: pnpm nx run @digikala/desktop:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            apps/desktop/release/*.exe
            apps/desktop/release/*.dmg
            apps/desktop/release/*.AppImage
            apps/desktop/release/*.zip
